/**
 * @rick/domain
 *
 * Core domain layer: entities, value objects, state machines, invariants,
 * and domain events. Framework-agnostic and infrastructure-free.
 *
 * Sprint 0 stub — domain models will be introduced in Sprint 1+.
 */

export type { ProjectId, ContractId, RunId, AuditId, Result, Ok, Err } from '@rick/shared'

export {
  DecisionStatus,
  hasBlockingDiagnostics,
  parseStrategicTruth,
  RequirementPriority,
  RequirementStatus,
  RequirementType,
  STRATEGIC_TRUTH_EXTRACTOR_VERSION,
} from './strategic-truth.js'
export type {
  DecisionCandidate,
  ExtractionDiagnostic,
  ExtractionDiagnosticCode,
  ExtractionDiagnosticSeverity,
  RequirementCandidate,
  StrategicSourceLocator,
  StrategicTruthCandidate,
} from './strategic-truth.js'

export {
  BacklogExternalProvider,
  canTransitionEpicStatus,
  canTransitionSprintStatus,
  canTransitionTaskStatus,
  EpicStatus,
  isDependencySatisfiedBy,
  isEpicPlanningMutable,
  isSprintPlanningMutable,
  isTaskPlanningMutable,
  isTerminalEpicStatus,
  isTerminalSprintStatus,
  isTerminalTaskStatus,
  normalizeBacklogCode,
  normalizeOptionalText,
  normalizeRequiredText,
  planningTransitionEffect,
  SprintStatus,
  TASK_PRIORITY_RANK,
  taskPriorityRank,
  TaskPriority,
  TaskStatus,
  taskTransitionEffect,
  TaskType,
  validateAcceptanceCriteria,
  validateExternalIdentity,
  validateSequence,
} from './operational-backlog.js'
export type {
  BacklogValidation,
  ExternalIdentityInput,
  LifecycleTimestampEffect,
} from './operational-backlog.js'

export {
  NEXT_WORK_RESOLVER_VERSION,
  NoEligibleWorkReason,
  resolveNextWork,
} from './next-work-resolver.js'
export type {
  CandidateStrategicContextInput,
  NextWorkRankingTuple,
  NextWorkResolverInput,
  NextWorkResolverResult,
  NoEligibleWorkResult,
  NoEligibleWorkReason as NoEligibleWorkReasonType,
  ResolverDecisionInput,
  ResolverDependencyInput,
  ResolverEpicInput,
  ResolverRequirementInput,
  ResolverSprintInput,
  ResolverStrategicSourceInput,
  ResolverTaskInput,
  SelectedNextWorkResult,
} from './next-work-resolver.js'

export {
  canonicalSpecContent,
  canTransitionImplementationSpecStatus,
  compareSpecVersions,
  evaluateSpecExecutionEligibility,
  formatSpecVersion,
  ImplementationSpecStatus,
  isImplementationSpecContentMutable,
  isSpecVersionGreater,
  isTerminalImplementationSpecStatus,
  normalizeSpecCode,
  normalizeSpecText,
  parseImplementationSpecContent,
  parseSpecVersion,
  SPEC_LIFECYCLE_VERSION,
  SpecEligibilityReason,
  SpecValidationCode,
  validateImplementationSpec,
  validateSpecStatements,
} from './implementation-spec.js'

export {
  ExecutionActorKind,
  ExecutionAgentRole,
  ExecutionCommandClass,
  ExecutionContractStatus,
  EXECUTION_CONTRACT_SCHEMA_VERSION,
  ExecutionMode,
  ExecutionPreconditionResult,
  ExecutionRiskLevel,
  parseExecutionContract,
  serializeExecutionContract,
} from './execution-contract.js'
export type {
  ApprovedImplementationSpecReference,
  ExecutionActorReference,
  ExecutionAgentAssignment,
  ExecutionApprovalGate,
  ExecutionCommandPolicy,
  ExecutionCompletionPolicy,
  ExecutionContract,
  ExecutionContractIdentity,
  ExecutionContractStatus as ExecutionContractStatusType,
  ExecutionContractValidation,
  ExecutionEvidenceRequirement,
  ExecutionGitPolicy,
  ExecutionJiraPolicy,
  ExecutionMode as ExecutionModeType,
  ExecutionObjectives,
  ExecutionPrecondition,
  ExecutionRecoveryPolicy,
  ExecutionRetryPolicy,
  ExecutionRiskAssessment,
  ExecutionRiskFinding,
  ExecutionScope,
  ExecutionScopeTargets,
  ExecutionSignature,
  ExecutionSourceSnapshot,
  ExecutionValidationGate,
  ExecutionWorkUnit,
  JsonObject,
  JsonValue,
  SourceDecisionReference,
  SourceDocumentReference,
  SourceJiraReference,
  SourceRepositorySnapshot,
  SourceRequirementReference,
  VersionedToolReference,
} from './execution-contract.js'
export type {
  CanonicalSpecInput,
  ImplementationSpecContent,
  ImplementationSpecContentInput,
  ImplementationSpecStatus as ImplementationSpecStatusType,
  SpecEligibilityFinding,
  SpecEligibilityInput,
  SpecEligibilityOutcome,
  SpecEligibilityReason as SpecEligibilityReasonType,
  SpecEligibilitySpecInput,
  SpecValidation,
  SpecValidationCode as SpecValidationCodeType,
  SpecValidationFinding,
  SpecValidationOutcome,
  SpecVersion,
} from './implementation-spec.js'

export {
  diagnoseReadiness,
  isReadinessDiagnosticBlockingTask,
  ReadinessDiagnosticCode,
  ReadinessDiagnosticSeverity,
  READINESS_DIAGNOSTICS_VERSION,
} from './readiness-diagnostics.js'
export type {
  AmbiguousCandidateOrderingDiagnostic,
  AmbiguousCandidateOrderingEvidence,
  AmbiguousCandidateOrderingEvidenceKey,
  BlockedDependencyDiagnostic,
  BlockedDependencyEvidence,
  InvalidProjectEvidence,
  InvalidProjectStateDiagnostic,
  InvalidProjectEvidenceKey,
  MissingRequiredInputDiagnostic,
  MissingRequiredInputEvidence,
  MissingRequiredInputEvidenceKey,
  ReadinessDiagnostic,
  ReadinessDiagnosticCode as ReadinessDiagnosticCodeType,
  ReadinessDiagnosticSeverity as ReadinessDiagnosticSeverityType,
  ReadinessSubject,
  ReadinessSubjectKind,
  StaleOrUnapprovedTruthDiagnostic,
  StaleOrUnapprovedTruthEvidence,
  StaleOrUnapprovedTruthEvidenceKey,
  StrategicConflictDiagnostic,
  StrategicConflictEvidence,
  StrategicConflictEvidenceKey,
} from './readiness-diagnostics.js'
